# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Menu")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Groupmenu = QtWidgets.QWidget(parent=self.centralwidget)
        self.Groupmenu.setGeometry(QtCore.QRect(610, 40, 116, 481))
        self.Groupmenu.setStyleSheet("QWidget {\n"
"background-color: rgb(0, 0, 0);\n"
"color: white;\n"
"}\n"
"\n"
"QPushButton {\n"
"height: 30px;\n"
"border: none;\n"
"}\n"
"")
        self.Groupmenu.setObjectName("Groupmenu")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Groupmenu)
        self.verticalLayout_6.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_14 = QtWidgets.QLabel(parent=self.Groupmenu)
        self.label_14.setMaximumSize(QtCore.QSize(159, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_5.addWidget(self.label_14)
        self.group = QtWidgets.QFrame(parent=self.Groupmenu)
        self.group.setStyleSheet("QPushButton {\n"
"padding: 10px;\n"
"};\n"
"\n"
"QPushButtonchecked {\n"
"background-color: white;\n"
"boder-radius: 3px;\n"
"}")
        self.group.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.group.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.group.setObjectName("group")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.group)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.dashbroad = QtWidgets.QPushButton(parent=self.group)
        self.dashbroad.setStyleSheet("QPushButton {\n"
"padding: 10px;\n"
"}\n"
"\n"
"QPushButton:checked {\n"
"    \n"
"    background-color: rgb(140, 0, 0);\n"
"border-radius: 3px;\n"
"\n"
"}")
        icon = QtGui.QIcon.fromTheme("menu")
        self.dashbroad.setIcon(icon)
        self.dashbroad.setCheckable(True)
        self.dashbroad.setChecked(False)
        self.dashbroad.setObjectName("dashbroad")
        self.verticalLayout_4.addWidget(self.dashbroad)
        self.group_dropdown = QtWidgets.QFrame(parent=self.group)
        self.group_dropdown.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.group_dropdown.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.group_dropdown.setObjectName("group_dropdown")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.group_dropdown)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.group1 = QtWidgets.QPushButton(parent=self.group_dropdown)
        self.group1.setStyleSheet("QPushButton {\n"
"padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color: rgb(255, 255, 0);\n"
"}")
        self.group1.setCheckable(True)
        self.group1.setObjectName("group1")
        self.verticalLayout_3.addWidget(self.group1)
        self.group2 = QtWidgets.QPushButton(parent=self.group_dropdown)
        self.group2.setStyleSheet("QPushButton {\n"
"padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color: rgb(255, 255, 0);\n"
"}")
        self.group2.setCheckable(True)
        self.group2.setObjectName("group2")
        self.verticalLayout_3.addWidget(self.group2)
        self.group3 = QtWidgets.QPushButton(parent=self.group_dropdown)
        self.group3.setStyleSheet("QPushButton {\n"
"padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"color: rgb(255, 255, 0);\n"
"}")
        self.group3.setCheckable(True)
        self.group3.setObjectName("group3")
        self.verticalLayout_3.addWidget(self.group3)
        self.verticalLayout_4.addWidget(self.group_dropdown)
        self.verticalLayout_5.addWidget(self.group)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.main = QtWidgets.QWidget(parent=self.centralwidget)
        self.main.setGeometry(QtCore.QRect(40, 40, 551, 481))
        self.main.setAutoFillBackground(False)
        self.main.setStyleSheet("\n"
"background-color: rgb(194, 255, 217);")
        self.main.setObjectName("main")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.main)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 20, 531, 451))
        self.stackedWidget.setObjectName("stackedWidget")
        self.group1_page = QtWidgets.QWidget()
        self.group1_page.setObjectName("group1_page")
        self.label_18 = QtWidgets.QLabel(parent=self.group1_page)
        self.label_18.setGeometry(QtCore.QRect(180, 150, 221, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.stackedWidget.addWidget(self.group1_page)
        self.group2_page = QtWidgets.QWidget()
        self.group2_page.setObjectName("group2_page")
        self.label_19 = QtWidgets.QLabel(parent=self.group2_page)
        self.label_19.setGeometry(QtCore.QRect(160, 150, 221, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.stackedWidget.addWidget(self.group2_page)
        self.group3_page = QtWidgets.QWidget()
        self.group3_page.setObjectName("group3_page")
        self.label_20 = QtWidgets.QLabel(parent=self.group3_page)
        self.label_20.setGeometry(QtCore.QRect(180, 150, 221, 121))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.stackedWidget.addWidget(self.group3_page)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.dashbroad.toggled['bool'].connect(self.group_dropdown.setHidden) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu"))
        self.label_14.setText(_translate("MainWindow", "Group"))
        self.dashbroad.setText(_translate("MainWindow", "Dashbroad"))
        self.group1.setText(_translate("MainWindow", "Group 1-6"))
        self.group2.setText(_translate("MainWindow", "Group 7-13"))
        self.group3.setText(_translate("MainWindow", "Group 14-20"))

        self.label_18.setText(_translate("MainWindow", "Group 1-6"))
        self.label_19.setText(_translate("MainWindow", "Group 7-13"))
        self.label_20.setText(_translate("MainWindow", "Group 14-20"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
