# Form implementation generated from reading ui file 'simulator_ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class SpeedGraphWidget(QtWidgets.QWidget):
        def __init__(self, parent=None):
                super().__init__(parent)
                self.speed_values = []
                self.maximum_samples = 60
                self.setMinimumSize(QtCore.QSize(300, 180))
                self.setAttribute(QtCore.Qt.WidgetAttribute.WA_TranslucentBackground)

        def set_speed(self, speed):
                self.speed_values.append(max(0.0, float(speed)))
                self.speed_values = self.speed_values[-self.maximum_samples:]
                self.update()

        def clear_data(self):
                self.speed_values.clear()
                self.update()

        def paintEvent(self, event):
                del event
                painter = QtGui.QPainter(self)
                painter.setRenderHint(QtGui.QPainter.RenderHint.Antialiasing)

                graph_area = self.rect().adjusted(42, 28, -14, -30)
                painter.setPen(QtGui.QPen(QtGui.QColor(30, 41, 59), 1))
                painter.drawText(12, 18, "Speed (m/s)")

                grid_pen = QtGui.QPen(QtGui.QColor(203, 213, 225), 1, QtCore.Qt.PenStyle.DotLine)
                painter.setPen(grid_pen)
                for grid_index in range(1, 5):
                        grid_y = graph_area.top() + graph_area.height() * grid_index / 5
                        painter.drawLine(graph_area.left(), int(grid_y), graph_area.right(), int(grid_y))
                for grid_index in range(1, 6):
                        grid_x = graph_area.left() + graph_area.width() * grid_index / 6
                        painter.drawLine(int(grid_x), graph_area.top(), int(grid_x), graph_area.bottom())

                painter.setPen(QtGui.QPen(QtGui.QColor(71, 85, 105), 1))
                painter.drawLine(graph_area.bottomLeft(), graph_area.topLeft())
                painter.drawLine(graph_area.bottomLeft(), graph_area.bottomRight())
                painter.drawText(graph_area.left() - 28, graph_area.bottom() + 20, "0")
                painter.drawText(graph_area.right() - 28, graph_area.bottom() + 20, "time")

                if not self.speed_values:
                        painter.setPen(QtGui.QColor(100, 116, 139))
                        painter.drawText(graph_area.center(), "Waiting for speed data...")
                        return

                maximum_speed = max(1.0, max(self.speed_values) * 1.2)
                painter.setPen(QtGui.QColor(100, 116, 139))
                painter.drawText(4, graph_area.top() + 5, f"{maximum_speed:.1f}")
                painter.drawText(18, graph_area.bottom(), "0")

                speed_points = QtGui.QPolygonF()
                for sample_index, speed in enumerate(self.speed_values):
                        if len(self.speed_values) == 1:
                                position_ratio = 1.0
                        else:
                                position_ratio = sample_index / (len(self.speed_values) - 1)
                        point_x = graph_area.left() + position_ratio * graph_area.width()
                        point_y = graph_area.bottom() - min(speed / maximum_speed, 1.0) * graph_area.height()
                        speed_points.append(QtCore.QPointF(point_x, point_y))

                painter.setPen(QtGui.QPen(QtGui.QColor(14, 116, 144), 2))
                painter.drawPolyline(speed_points)
                painter.setBrush(QtGui.QColor(14, 116, 144))
                last_point = speed_points.at(speed_points.size() - 1)
                painter.drawEllipse(last_point, 3, 3)


class Ui_MainWindow(object):
    def __init__(self, rack_group_id = 1, left=0, top=0, width=1030, height=725):
        super().__init__()
        self.rack_group_id = rack_group_id
        self.left = left
        self.top = top
        self.width = width
        self.height = height
        self.rackGroupList = []

    def create_layout_rack_group(self, number):
        rackGroup = MyGroupBox(rack_group_id=number+1, left=self.left, top=self.top+(self.height+20)*number, width=self.width, height=self.height)
        self.rackGroupList.append(rackGroup)
        return rackGroup.rackGroup

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 760)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.groupSelector = QtWidgets.QListWidget(parent=self.centralwidget)
        self.groupSelector.setFixedWidth(155)
        self.groupSelector.setObjectName("groupSelector")
        self.groupSelector.setStyleSheet(
                        "QListWidget { background-color: transparent; border: none; font-size: 11pt; }"
                        "QListWidget::viewport { background-color: transparent; }"
            "QListWidget::item { padding: 9px 6px; }"
            "QListWidget::item:selected { background-color: #1976d2; color: white; }"
        )

        self.groupStack = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.groupStack.setMinimumSize(QtCore.QSize(1000, 700))
        self.groupStack.setObjectName("groupStack")

        for i in range(21):
            group_widget = self.create_layout_rack_group(i)
            self.groupStack.addWidget(group_widget)
            self.groupSelector.addItem(f"GROUP {i + 1}")

        self.groupSelector.setCurrentRow(0)
        self.groupSelector.currentRowChanged.connect(self.groupStack.setCurrentIndex)

        self.scrollArea = QtWidgets.QScrollArea()
        self.scrollArea.setWidget(self.groupStack)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)

        self.vBoxLayout = QtWidgets.QHBoxLayout()
        self.vBoxLayout.setContentsMargins(6, 6, 6, 6)
        self.vBoxLayout.addWidget(self.groupSelector)
        self.vBoxLayout.addWidget(self.scrollArea, 1)

        self.centralwidget.setLayout(self.vBoxLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 752, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate

        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        for i in range(21):
            self.rackGroupList[i].retranslateUi()

class MyGroupBox:
    def __init__(self, rack_group_id, left, top, width, height):
        super().__init__()
        self.rack_group_id = rack_group_id

        self.rackGroup = QtWidgets.QGroupBox()
        self.rackGroup.setGeometry(QtCore.QRect(10, 10, 1000, 700))
        self.rackGroup.setMinimumSize(QtCore.QSize(1000, 700))
        self.rackGroup.setMaximumSize(QtCore.QSize(1000, 750))
        self.rackGroup.setObjectName("rackGroup")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.rackGroup)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Layout = QtWidgets.QVBoxLayout()
        self.Layout.setObjectName("Layout")
        self.rackGroupImage = QtWidgets.QLabel(parent=self.rackGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rackGroupImage.sizePolicy().hasHeightForWidth())
        self.rackGroupImage.setSizePolicy(sizePolicy)
        self.rackGroupImage.setMaximumSize(QtCore.QSize(825, 185))
        self.rackGroupImage.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.rackGroupImage.setText("")
        self.rackGroupImage.setPixmap(QtGui.QPixmap("Simulation/Image/RackGroup/Default.png"))
        self.rackGroupImage.setScaledContents(True)
        self.rackGroupImage.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.rackGroupImage.setWordWrap(False)
        self.rackGroupImage.setObjectName("rackGroupImage")
        self.Layout.addWidget(self.rackGroupImage)
        self.Group_one_2 = QtWidgets.QWidget(parent=self.rackGroup)
        self.Group_one_2.setMaximumSize(QtCore.QSize(16777215, 140))
        self.Group_one_2.setObjectName("Group_one_2")
        self.Group_one = QtWidgets.QHBoxLayout(self.Group_one_2)
        self.Group_one.setContentsMargins(0, 5, 0, 5)
        self.Group_one.setObjectName("Group_one")
        self.idGroup_2 = QtWidgets.QGroupBox(parent=self.Group_one_2)
        self.idGroup_2.setMinimumSize(QtCore.QSize(400, 0))
        self.idGroup_2.setMaximumSize(QtCore.QSize(420, 16777215))
        self.idGroup_2.setObjectName("idGroup_2")
        self.idGroup = QtWidgets.QVBoxLayout(self.idGroup_2)
        self.idGroup.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.idGroup.setSpacing(0)
        self.idGroup.setObjectName("idGroup")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setSpacing(0)
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.groupBox_17 = QtWidgets.QGroupBox(parent=self.idGroup_2)
        self.groupBox_17.setMinimumSize(QtCore.QSize(380, 70))
        self.groupBox_17.setMaximumSize(QtCore.QSize(400, 70))
        self.groupBox_17.setFlat(True)
        self.groupBox_17.setStyleSheet("QGroupBox { background-color: transparent; }")
        self.groupBox_17.setObjectName("groupBox_17")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.rackButtonLayout = QtWidgets.QHBoxLayout()
        self.rackButtonLayout.setSpacing(5)
        self.rackButtonLayout.setObjectName("rackButtonLayout")
        self.rackButtons = []
        self.selected_rack_id = (self.rack_group_id - 1) * 6 + 1
        for rack_number in range(6):
            rack_id = (self.rack_group_id - 1) * 6 + rack_number + 1
            rack_button = QtWidgets.QPushButton(str(rack_id), parent=self.groupBox_17)
            rack_button.setFixedSize(42, 42)
            rack_button.setCheckable(True)
            rack_button.setStyleSheet(
                                "QPushButton { background-color: white; border: 1px solid #94a3b8; border-radius: 4px; }"
                "QPushButton:checked { background-color: #1976d2; color: white; border: 2px solid #0f4c81; }"
            )
            rack_button.setObjectName(f"rackButton{rack_id}")
            self.rackButtons.append(rack_button)
            self.rackButtonLayout.addWidget(rack_button)
        self.rackButtons[0].setChecked(True)
        self.verticalLayout_32.addLayout(self.rackButtonLayout)
        self.Button = QtWidgets.QWidget(parent=self.idGroup_2)
        self.Button.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Button.setObjectName("Button")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.Button)
        self.horizontalLayout_23.setContentsMargins(-1, 1, -1, -1)
        self.horizontalLayout_23.setSpacing(7)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.runButton = QtWidgets.QPushButton(parent=self.Button)
        self.runButton.setMinimumSize(QtCore.QSize(150, 0))
        self.runButton.setMaximumSize(QtCore.QSize(16777215, 28))
        self.runButton.setCheckable(False)
        self.runButton.setChecked(False)
        self.runButton.setObjectName("runButton")
        self.horizontalLayout_23.addWidget(self.runButton, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.stopButton = QtWidgets.QPushButton(parent=self.Button)
        self.stopButton.setMinimumSize(QtCore.QSize(150, 0))
        self.stopButton.setMaximumSize(QtCore.QSize(200, 28))
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_23.addWidget(self.stopButton, 0, QtCore.Qt.AlignmentFlag.AlignLeft)
        self.idGroup.addWidget(self.Button)
        self.horizontalLayout_49.addWidget(self.groupBox_17)
        self.idGroup.addLayout(self.horizontalLayout_49)
        self.Group_one.addWidget(self.idGroup_2)
        self.stateGroup_2 = QtWidgets.QWidget(parent=self.Group_one_2)
        self.stateGroup_2.setMinimumSize(QtCore.QSize(500, 0))
        self.stateGroup_2.setMaximumSize(QtCore.QSize(500, 16777215))
        self.stateGroup_2.setObjectName("stateGroup_2")
        self.stateGroup = QtWidgets.QHBoxLayout(self.stateGroup_2)
        self.stateGroup.setSpacing(0)
        self.stateGroup.setObjectName("stateGroup")
        self.State = QtWidgets.QLabel(parent=self.stateGroup_2)
        self.State.setMinimumSize(QtCore.QSize(40, 30))
        self.State.setMaximumSize(QtCore.QSize(16777215, 30))
        self.State.setObjectName("State")
        self.stateGroup.addWidget(self.State)
        self.rackGroupStateLineEdit = QtWidgets.QLineEdit(parent=self.stateGroup_2)
        self.rackGroupStateLineEdit.setMinimumSize(QtCore.QSize(0, 25))
        self.rackGroupStateLineEdit.setMaximumSize(QtCore.QSize(16777215, 35))
        self.rackGroupStateLineEdit.setStyleSheet("QLineEdit{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.rackGroupStateLineEdit.setText("")
        self.rackGroupStateLineEdit.setObjectName("rackGroupStateLineEdit")
        self.stateGroup.addWidget(self.rackGroupStateLineEdit)
        self.Group_one.addWidget(self.stateGroup_2)
        self.Layout.addWidget(self.Group_one_2)
        self.Group_two = QtWidgets.QWidget(parent=self.rackGroup)
        self.Group_two.setEnabled(True)
        self.Group_two.setMaximumSize(QtCore.QSize(16777215, 350))
        self.Group_two.setAcceptDrops(False)
        self.Group_two.setStyleSheet("")
        self.Group_two.setObjectName("Group_two")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Group_two)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ENVGroup = QtWidgets.QGroupBox(parent=self.Group_two)
        self.ENVGroup.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ENVGroup.setObjectName("ENVGroup")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.ENVGroup)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.tempGroup = QtWidgets.QGroupBox(parent=self.ENVGroup)
        self.tempGroup.setMaximumSize(QtCore.QSize(16777215, 100))
        self.tempGroup.setObjectName("tempGroup")
        self.temp = QtWidgets.QHBoxLayout(self.tempGroup)
        self.temp.setObjectName("temp")
        self.label_59 = QtWidgets.QLabel(parent=self.tempGroup)
        self.label_59.setMaximumSize(QtCore.QSize(50, 50))
        self.label_59.setText("")
        self.label_59.setPixmap(QtGui.QPixmap("Simulation/Draft/Image/ENV/temp.png"))
        self.label_59.setScaledContents(True)
        self.label_59.setWordWrap(False)
        self.label_59.setOpenExternalLinks(False)
        self.label_59.setObjectName("label_59")
        self.temp.addWidget(self.label_59)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_60 = QtWidgets.QLabel(parent=self.tempGroup)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_8.addWidget(self.label_60)
        self.temperature = QtWidgets.QLCDNumber(parent=self.tempGroup)
        self.temperature.setMaximumSize(QtCore.QSize(16777215, 35))
        self.temperature.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.temperature.setSmallDecimalPoint(False)
        self.temperature.setSegmentStyle(QtWidgets.QLCDNumber.SegmentStyle.Filled)
        self.temperature.setObjectName("temperature")
        self.verticalLayout_8.addWidget(self.temperature)
        self.temp.addLayout(self.verticalLayout_8)
        self.verticalLayout_35.addWidget(self.tempGroup)
        self.lightGroup = QtWidgets.QGroupBox(parent=self.ENVGroup)
        self.lightGroup.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lightGroup.setObjectName("lightGroup")
        self.humidity = QtWidgets.QHBoxLayout(self.lightGroup)
        self.humidity.setObjectName("humidity")
        self.label_61 = QtWidgets.QLabel(parent=self.lightGroup)
        self.label_61.setMaximumSize(QtCore.QSize(50, 50))
        self.label_61.setText("")
        self.label_61.setPixmap(QtGui.QPixmap("Simulation/Draft/Image/ENV/smoke.png"))
        self.label_61.setScaledContents(True)
        self.label_61.setWordWrap(False)
        self.label_61.setOpenExternalLinks(False)
        self.label_61.setObjectName("label_61")
        self.humidity.addWidget(self.label_61)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_62 = QtWidgets.QLabel(parent=self.lightGroup)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_9.addWidget(self.label_62)
        self.smoke = QtWidgets.QLCDNumber(parent=self.lightGroup)
        self.smoke.setMaximumSize(QtCore.QSize(16777215, 35))
        self.smoke.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.smoke.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.smoke.setObjectName("smoke")
        self.verticalLayout_9.addWidget(self.smoke)
        self.humidity.addLayout(self.verticalLayout_9)
        self.verticalLayout_35.addWidget(self.lightGroup)
        self.horizontalLayout_50.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.weightGroup = QtWidgets.QGroupBox(parent=self.ENVGroup)
        self.weightGroup.setMaximumSize(QtCore.QSize(16777215, 100))
        self.weightGroup.setObjectName("weightGroup")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.weightGroup)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_63 = QtWidgets.QLabel(parent=self.weightGroup)
        self.label_63.setMaximumSize(QtCore.QSize(50, 50))
        self.label_63.setText("")
        self.label_63.setPixmap(QtGui.QPixmap("Simulation/Draft/Image/ENV/weight.png"))
        self.label_63.setScaledContents(True)
        self.label_63.setWordWrap(False)
        self.label_63.setOpenExternalLinks(False)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_52.addWidget(self.label_63)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_64 = QtWidgets.QLabel(parent=self.weightGroup)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_10.addWidget(self.label_64)
        self.weight = QtWidgets.QLCDNumber(parent=self.weightGroup)
        self.weight.setMaximumSize(QtCore.QSize(16777215, 35))
        self.weight.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.weight.setObjectName("weight")
        self.verticalLayout_10.addWidget(self.weight)
        self.horizontalLayout_52.addLayout(self.verticalLayout_10)
        self.verticalLayout_36.addWidget(self.weightGroup)
        self.lightGroup = QtWidgets.QGroupBox(parent=self.ENVGroup)
        self.lightGroup.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lightGroup.setObjectName("lightGroup")
        self.horizontalLayout_53 = QtWidgets.QHBoxLayout(self.lightGroup)
        self.horizontalLayout_53.setObjectName("horizontalLayout_53")
        self.label_65 = QtWidgets.QLabel(parent=self.lightGroup)
        self.label_65.setMaximumSize(QtCore.QSize(50, 50))
        self.label_65.setText("")
        self.label_65.setPixmap(QtGui.QPixmap("Simulation/Draft/Image/OPR/light.png"))
        self.label_65.setScaledContents(True)
        self.label_65.setWordWrap(False)
        self.label_65.setOpenExternalLinks(False)
        self.label_65.setObjectName("label_65")
        self.horizontalLayout_53.addWidget(self.label_65)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_66 = QtWidgets.QLabel(parent=self.lightGroup)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_11.addWidget(self.label_66)
        self.light = QtWidgets.QLCDNumber(parent=self.lightGroup)
        self.light.setMaximumSize(QtCore.QSize(16777215, 35))
        self.light.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.light.setObjectName("light")
        self.verticalLayout_11.addWidget(self.light)
        self.horizontalLayout_53.addLayout(self.verticalLayout_11)
        self.verticalLayout_36.addWidget(self.lightGroup)
        self.horizontalLayout_50.addLayout(self.verticalLayout_36)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.humidityGroup = QtWidgets.QGroupBox(parent=self.ENVGroup)
        self.humidityGroup.setMaximumSize(QtCore.QSize(16777215, 100))
        self.humidityGroup.setObjectName("humidityGroup")
        self.humidity_5 = QtWidgets.QHBoxLayout(self.humidityGroup)
        self.humidity_5.setObjectName("humidity_5")
        self.label_89 = QtWidgets.QLabel(parent=self.humidityGroup)
        self.label_89.setMaximumSize(QtCore.QSize(50, 50))
        self.label_89.setText("")
        self.label_89.setPixmap(QtGui.QPixmap("Simulation/Draft/Image/ENV/humidity.png"))
        self.label_89.setScaledContents(True)
        self.label_89.setWordWrap(False)
        self.label_89.setOpenExternalLinks(False)
        self.label_89.setObjectName("label_89")
        self.humidity_5.addWidget(self.label_89)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_90 = QtWidgets.QLabel(parent=self.humidityGroup)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_12.addWidget(self.label_90)
        self.humidity = QtWidgets.QLCDNumber(parent=self.humidityGroup)
        self.humidity.setMaximumSize(QtCore.QSize(16777215, 35))
        self.humidity.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.humidity.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.humidity.setObjectName("humidity")
        self.verticalLayout_12.addWidget(self.humidity)
        self.humidity_5.addLayout(self.verticalLayout_12)
        self.verticalLayout_4.addWidget(self.humidityGroup)
        self.lockedGroup_2 = QtWidgets.QGroupBox(parent=self.ENVGroup)
        self.lockedGroup_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.lockedGroup_2.setObjectName("lockedGroup_2")
        self.lockedGroup = QtWidgets.QHBoxLayout(self.lockedGroup_2)
        self.lockedGroup.setObjectName("lockedGroup")
        self.label_91 = QtWidgets.QLabel(parent=self.lockedGroup_2)
        self.label_91.setMaximumSize(QtCore.QSize(50, 50))
        self.label_91.setText("")
        self.label_91.setPixmap(QtGui.QPixmap("Simulation/Draft/Image/OPR/locked.png"))
        self.label_91.setScaledContents(True)
        self.label_91.setWordWrap(False)
        self.label_91.setOpenExternalLinks(False)
        self.label_91.setObjectName("label_91")
        self.lockedGroup.addWidget(self.label_91)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_92 = QtWidgets.QLabel(parent=self.lockedGroup_2)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_13.addWidget(self.label_92)
        self.isHardLock = QtWidgets.QLCDNumber(parent=self.lockedGroup_2)
        self.isHardLock.setMaximumSize(QtCore.QSize(16777215, 35))
        self.isHardLock.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.isHardLock.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.isHardLock.setObjectName("isHardLock")
        self.verticalLayout_13.addWidget(self.isHardLock)
        self.lockedGroup.addLayout(self.verticalLayout_13)
        self.verticalLayout_4.addWidget(self.lockedGroup_2)
        self.horizontalLayout_50.addLayout(self.verticalLayout_4)
        self.verticalLayout_34.addLayout(self.horizontalLayout_50)
        self.horizontalLayout.addWidget(self.ENVGroup)
        self.OPR_ERR = QtWidgets.QGroupBox(parent=self.Group_two)
        self.OPR_ERR.setMinimumSize(QtCore.QSize(500, 0))
        self.OPR_ERR.setMaximumSize(QtCore.QSize(500, 16777215))
        self.OPR_ERR.setObjectName("OPR_ERR")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.OPR_ERR)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.OPRGroup = QtWidgets.QHBoxLayout()
        self.OPRGroup.setObjectName("OPRGroup")
        self.OPR = QtWidgets.QGroupBox(parent=self.OPR_ERR)
        self.OPR.setMaximumSize(QtCore.QSize(150, 250))
        self.OPR.setObjectName("OPR")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.OPR)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Speed = QtWidgets.QGroupBox(parent=self.OPR)
        self.Speed.setMaximumSize(QtCore.QSize(150, 101))
        self.Speed.setFlat(True)
        self.Speed.setObjectName("Speed")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.Speed)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.movementSpeed = QtWidgets.QLCDNumber(parent=self.Speed)
        self.movementSpeed.setMinimumSize(QtCore.QSize(0, 30))
        self.movementSpeed.setMaximumSize(QtCore.QSize(150, 35))
        self.movementSpeed.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.movementSpeed.setObjectName("movementSpeed")
        self.verticalLayout_40.addWidget(self.movementSpeed)
        self.verticalLayout_2.addWidget(self.Speed)
        self.Place = QtWidgets.QGroupBox(parent=self.OPR)
        self.Place.setMaximumSize(QtCore.QSize(150, 101))
        self.Place.setFlat(True)
        self.Place.setObjectName("Place")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.Place)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.displacement = QtWidgets.QLCDNumber(parent=self.Place)
        self.displacement.setMinimumSize(QtCore.QSize(0, 30))
        self.displacement.setMaximumSize(QtCore.QSize(150, 35))
        self.displacement.setStyleSheet("QLCDNumber{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.displacement.setObjectName("displacement")
        self.verticalLayout_37.addWidget(self.displacement)
        self.verticalLayout_2.addWidget(self.Place)
        self.OPRGroup.addWidget(self.OPR)
        self.graphGroup = QtWidgets.QGroupBox(parent=self.OPR_ERR)
        self.graphGroup.setMinimumSize(QtCore.QSize(340, 0))
        self.graphGroup.setObjectName("graphGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.graphGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.speedGraph = SpeedGraphWidget(parent=self.graphGroup)
        self.speedGraph.setObjectName("speedGraph")
        self.verticalLayout_5.addWidget(self.speedGraph)
        self.OPRGroup.addWidget(self.graphGroup)
        self.verticalLayout.addLayout(self.OPRGroup)
        self.errorGroup = QtWidgets.QWidget(parent=self.OPR_ERR)
        self.errorGroup.setMaximumSize(QtCore.QSize(16777215, 130))
        self.errorGroup.setObjectName("errorGroup")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.errorGroup)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.errorCheckBox = QtWidgets.QHBoxLayout()
        self.errorCheckBox.setSpacing(0)
        self.errorCheckBox.setObjectName("errorCheckBox")
        self.ObstructCheckBox = QtWidgets.QCheckBox(parent=self.errorGroup)
        self.ObstructCheckBox.setObjectName("ObstructCheckBox")
        self.errorCheckBox.addWidget(self.ObstructCheckBox)
        self.OverloadMotorCheckBox = QtWidgets.QCheckBox(parent=self.errorGroup)
        self.OverloadMotorCheckBox.setObjectName("OverloadMotorCheckBox")
        self.errorCheckBox.addWidget(self.OverloadMotorCheckBox)
        self.SkewCheckBox = QtWidgets.QCheckBox(parent=self.errorGroup)
        self.SkewCheckBox.setObjectName("SkewCheckBox")
        self.errorCheckBox.addWidget(self.SkewCheckBox)
        self.simulatorErrorButton = QtWidgets.QPushButton(parent=self.errorGroup)
        self.simulatorErrorButton.setMinimumSize(QtCore.QSize(0, 30))
        self.simulatorErrorButton.setObjectName("simulatorErrorButton")
        self.errorCheckBox.addWidget(self.simulatorErrorButton)
        self.verticalLayout_38.addLayout(self.errorCheckBox)
        self.errorState = QtWidgets.QHBoxLayout()
        self.errorState.setObjectName("errorState")
        self.error = QtWidgets.QLabel(parent=self.errorGroup)
        self.error.setMinimumSize(QtCore.QSize(40, 35))
        self.error.setMaximumSize(QtCore.QSize(40, 30))
        self.error.setObjectName("error")
        self.errorState.addWidget(self.error)
        self.rackGroupErrorLineEdit = QtWidgets.QLineEdit(parent=self.errorGroup)
        self.rackGroupErrorLineEdit.setMinimumSize(QtCore.QSize(0, 35))
        self.rackGroupErrorLineEdit.setStyleSheet("QLineEdit{\n"
"  background-color: rgb(0, 0, 0);\n"
"  color: rgb(255, 255, 255);\n"
"}")
        self.rackGroupErrorLineEdit.setObjectName("rackGroupErrorLineEdit")
        self.errorState.addWidget(self.rackGroupErrorLineEdit)
        self.verticalLayout_38.addLayout(self.errorState)
        self.verticalLayout.addWidget(self.errorGroup)
        self.horizontalLayout.addWidget(self.OPR_ERR)
        self.Layout.addWidget(self.Group_two)
        self.verticalLayout_7.addLayout(self.Layout)

        
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate

        self.rackGroup.setTitle(_translate("MainWindow", "GROUP "+ str(self.rack_group_id)))
        self.groupBox_17.setTitle(_translate("MainWindow", "Rack ID"))

        self.runButton.setText(_translate("MainWindow", "Start Simulating"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        
        self.State.setText(_translate("MainWindow", "STATE "))
        self.ENVGroup.setTitle(_translate("MainWindow", "ENV"))
        self.label_60.setText(_translate("MainWindow", "Temperature"))
        self.label_62.setText(_translate("MainWindow", "Smoke"))
        self.label_64.setText(_translate("MainWindow", "Weight"))
        self.label_66.setText(_translate("MainWindow", "Light"))
        self.label_90.setText(_translate("MainWindow", "Humidity"))
        self.label_92.setText(_translate("MainWindow", "Hard Locked"))
        self.OPR_ERR.setTitle(_translate("MainWindow", "OPR"))
        self.Speed.setTitle(_translate("MainWindow", "SPEED "))
        self.Place.setTitle(_translate("MainWindow", "DISPLACEMENT "))
        self.ObstructCheckBox.setText(_translate("MainWindow", "Obstruct"))
        self.OverloadMotorCheckBox.setText(_translate("MainWindow", "Overload"))
        self.SkewCheckBox.setText(_translate("MainWindow", "Skew"))
        self.simulatorErrorButton.setText(_translate("MainWindow", "Simulate Error"))
        self.error.setText(_translate("MainWindow", "ERROR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
